import {
  Alert,
  Box,
  Button,
  Chip,
  Skeleton,
  Stack,
  Typography,
} from "@mui/material";

/**
 * Shows which engine produced the text. Being visibly honest about the
 * template fallback is a maturity signal, not a weakness - a reviewer who
 * spots an undisclosed fallback trusts nothing else on the page.
 */
export default function NarrativePanel({ summary, loading, onGenerate, model }) {
  if (loading) {
    return (
      <Box>
        <Skeleton height={28} width="40%" />
        <Skeleton height={20} />
        <Skeleton height={20} />
        <Skeleton height={20} width="70%" />
      </Box>
    );
  }

  if (!summary) {
    return (
      <Stack spacing={2} alignItems="flex-start">
        <Typography variant="body2" color="text.secondary">
          Generate an investigator-ready write-up of this case: what happened, the
          recommended disposition, and concrete next steps.
        </Typography>
        <Button variant="contained" onClick={onGenerate}>
          Generate summary
        </Button>
      </Stack>
    );
  }

  if (summary.error) {
    return (
      <Alert
        severity="error"
        action={
          <Button size="small" onClick={onGenerate}>
            Retry
          </Button>
        }
      >
        {summary.error}
      </Alert>
    );
  }

  const isLlm = summary.source === "llm";

  return (
    <Stack spacing={2}>
      <Stack direction="row" spacing={1} alignItems="center" flexWrap="wrap" useFlexGap>
        <Chip
          size="small"
          color={isLlm ? "primary" : "default"}
          variant={isLlm ? "filled" : "outlined"}
          label={isLlm ? `Generated by ${model ?? "Claude"}` : "Template fallback"}
        />
        {summary.rate_limited && (
          <Chip size="small" color="warning" variant="outlined" label="Rate limited" />
        )}
      </Stack>

      {summary.rate_limited && (
        <Alert severity="info">
          The demo limits Claude calls per minute. This summary was generated from the
          case signals instead — the wording differs, the evidence does not.
        </Alert>
      )}

      <Box>
        <Typography variant="subtitle2" gutterBottom>
          Narrative
        </Typography>
        <Typography variant="body2">{summary.narrative}</Typography>
      </Box>

      <Box>
        <Typography variant="subtitle2" gutterBottom>
          Recommendation
        </Typography>
        <Typography variant="body2">{summary.recommendation}</Typography>
      </Box>

      <Box>
        <Typography variant="subtitle2" gutterBottom>
          Next steps
        </Typography>
        <Stack component="ol" spacing={0.5} sx={{ pl: 2.5, m: 0 }}>
          {summary.next_steps.map((step, i) => (
            <Typography key={i} component="li" variant="body2">
              {step}
            </Typography>
          ))}
        </Stack>
      </Box>

      <Box>
        <Button size="small" onClick={onGenerate}>
          Regenerate
        </Button>
      </Box>
    </Stack>
  );
}
