import {
  Box,
  Chip,
  LinearProgress,
  Stack,
  Tooltip,
  Typography,
} from "@mui/material";

/**
 * The case's evidence, and the whole argument of the demo: it turns an opaque
 * number into a list of reasons a human can check.
 *
 * Each signal shows its contribution to the score, the sentence explaining what
 * fired (generated by the rule, containing the actual numbers), and chips for
 * the transactions it implicates. Clicking a chip highlights that row in the
 * transactions table.
 */
export default function SignalPanel({ signals, onSelectTransaction }) {
  if (!signals?.length) {
    return (
      <Typography variant="body2" color="text.secondary">
        No signals recorded for this case.
      </Typography>
    );
  }

  return (
    <Stack spacing={2.5}>
      {signals.map((s) => (
        <Box key={s.rule}>
          <Box display="flex" justifyContent="space-between" alignItems="baseline" gap={2}>
            <Typography variant="subtitle2">
              {s.label}
              {s.instances > 1 && (
                <Typography component="span" variant="caption" color="text.secondary">
                  {" "}×{s.instances}
                </Typography>
              )}
            </Typography>
            <Tooltip
              title={
                s.instances > 1
                  ? `${s.instances} occurrences combined; strongest is ` +
                    `weight ${s.weight.toFixed(2)} × strength ${s.score.toFixed(2)}`
                  : `weight ${s.weight.toFixed(2)} × strength ${s.score.toFixed(2)}`
              }
            >
              <Typography variant="caption" color="text.secondary" noWrap>
                contributes {s.contribution.toFixed(2)}
              </Typography>
            </Tooltip>
          </Box>

          <LinearProgress
            variant="determinate"
            value={Math.min(100, s.contribution * 100)}
            sx={{ my: 0.75, height: 6, borderRadius: 3 }}
          />

          <Typography variant="body2" color="text.secondary">
            {s.explanation}
          </Typography>

          {s.tx_ids?.length > 0 && (
            <Stack direction="row" spacing={0.5} flexWrap="wrap" useFlexGap sx={{ mt: 1 }}>
              {s.tx_ids.map((id) => (
                <Chip
                  key={id}
                  label={id}
                  size="small"
                  variant="outlined"
                  onClick={() => onSelectTransaction?.(id)}
                  sx={{ fontFamily: "monospace", fontSize: 11 }}
                />
              ))}
            </Stack>
          )}
        </Box>
      ))}
    </Stack>
  );
}
