import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";

import NarrativePanel from "../NarrativePanel";

const SUMMARY = {
  case_id: "CASE-1",
  narrative: "Three customers shared one device.",
  recommendation: "Freeze the accounts.",
  next_steps: ["Freeze", "Call the customer"],
  source: "llm",
};

describe("NarrativePanel", () => {
  it("offers to generate when there is no summary yet", async () => {
    const onGenerate = vi.fn();
    render(<NarrativePanel onGenerate={onGenerate} />);
    await userEvent.click(screen.getByRole("button", { name: /generate summary/i }));
    expect(onGenerate).toHaveBeenCalled();
  });

  it("renders narrative, recommendation and steps", () => {
    render(<NarrativePanel summary={SUMMARY} />);
    expect(screen.getByText(SUMMARY.narrative)).toBeInTheDocument();
    expect(screen.getByText(SUMMARY.recommendation)).toBeInTheDocument();
    expect(screen.getByText("Call the customer")).toBeInTheDocument();
  });

  /**
   * Disclosure matters: a reviewer who finds an undisclosed template fallback
   * stops trusting everything else the page claims.
   */
  it("names the model when the summary came from the LLM", () => {
    render(<NarrativePanel summary={SUMMARY} model="claude-haiku-4-5" />);
    expect(screen.getByText(/Generated by claude-haiku-4-5/)).toBeInTheDocument();
  });

  it("says so plainly when the summary came from the template", () => {
    render(<NarrativePanel summary={{ ...SUMMARY, source: "template" }} />);
    expect(screen.getByText(/Template fallback/)).toBeInTheDocument();
  });

  it("explains a rate-limited fallback", () => {
    render(
      <NarrativePanel summary={{ ...SUMMARY, source: "template", rate_limited: true }} />
    );
    expect(screen.getByText(/Rate limited/)).toBeInTheDocument();
    expect(screen.getByText(/limits Claude calls per minute/i)).toBeInTheDocument();
  });

  it("offers a retry when generation failed", async () => {
    const onGenerate = vi.fn();
    render(<NarrativePanel summary={{ error: "upstream 529" }} onGenerate={onGenerate} />);
    expect(screen.getByText("upstream 529")).toBeInTheDocument();
    await userEvent.click(screen.getByRole("button", { name: /retry/i }));
    expect(onGenerate).toHaveBeenCalled();
  });

  it("shows a skeleton while loading", () => {
    const { container } = render(<NarrativePanel loading />);
    expect(container.querySelectorAll(".MuiSkeleton-root").length).toBeGreaterThan(0);
  });
});
